[package]
name = "preproc_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
quick-xml = "0.27.1"
indicatif = { version = "0.17.3", features = ["rayon"] }
chrono = "0.4.23"
